/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_io.h"

static const char* CMockString_addr = "addr";
static const char* CMockString_data = "data";
static const char* CMockString_uxIORead = "uxIORead";
static const char* CMockString_vIOWrite = "vIOWrite";

typedef struct _CMOCK_uxIORead_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ioData ReturnVal;
  int CallOrder;
  ioAddress Expected_addr;
  char IgnoreArg_addr;

} CMOCK_uxIORead_CALL_INSTANCE;

typedef struct _CMOCK_vIOWrite_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  ioAddress Expected_addr;
  ioData Expected_data;
  char IgnoreArg_addr;
  char IgnoreArg_data;

} CMOCK_vIOWrite_CALL_INSTANCE;

static struct mock_ioInstance
{
  char uxIORead_IgnoreBool;
  ioData uxIORead_FinalReturn;
  char uxIORead_CallbackBool;
  CMOCK_uxIORead_CALLBACK uxIORead_CallbackFunctionPointer;
  int uxIORead_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE uxIORead_CallInstance;
  char vIOWrite_IgnoreBool;
  char vIOWrite_CallbackBool;
  CMOCK_vIOWrite_CALLBACK vIOWrite_CallbackFunctionPointer;
  int vIOWrite_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vIOWrite_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_io_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.uxIORead_CallInstance;
  if (Mock.uxIORead_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uxIORead);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.uxIORead_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.vIOWrite_CallInstance;
  if (Mock.vIOWrite_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_vIOWrite);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.vIOWrite_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_io_Init(void)
{
  mock_io_Destroy();
}

void mock_io_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

ioData uxIORead(ioAddress addr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uxIORead_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uxIORead);
  cmock_call_instance = (CMOCK_uxIORead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uxIORead_CallInstance);
  Mock.uxIORead_CallInstance = CMock_Guts_MemNext(Mock.uxIORead_CallInstance);
  if (Mock.uxIORead_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.uxIORead_FinalReturn;
    memcpy((void*)(&Mock.uxIORead_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(ioData[sizeof(cmock_call_instance->ReturnVal) == sizeof(ioData) ? 1 : -1])); /* add ioData to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.uxIORead_CallbackBool &&
      Mock.uxIORead_CallbackFunctionPointer != NULL)
  {
    ioData cmock_cb_ret = Mock.uxIORead_CallbackFunctionPointer(addr, Mock.uxIORead_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_addr)
  {
    UNITY_SET_DETAILS(CMockString_uxIORead,CMockString_addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_addr), (void*)(&addr), sizeof(ioAddress), cmock_line, CMockStringMismatch);
  }
  if (Mock.uxIORead_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.uxIORead_CallbackFunctionPointer(addr, Mock.uxIORead_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uxIORead(CMOCK_uxIORead_CALL_INSTANCE* cmock_call_instance, ioAddress addr);
void CMockExpectParameters_uxIORead(CMOCK_uxIORead_CALL_INSTANCE* cmock_call_instance, ioAddress addr)
{
  memcpy((void*)(&cmock_call_instance->Expected_addr), (void*)(&addr),
         sizeof(ioAddress[sizeof(addr) == sizeof(ioAddress) ? 1 : -1])); /* add ioAddress to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_addr = 0;
}

void uxIORead_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ioData cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uxIORead_CALL_INSTANCE));
  CMOCK_uxIORead_CALL_INSTANCE* cmock_call_instance = (CMOCK_uxIORead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uxIORead_CallInstance = CMock_Guts_MemChain(Mock.uxIORead_CallInstance, cmock_guts_index);
  Mock.uxIORead_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.uxIORead_IgnoreBool = (char)1;
}

void uxIORead_CMockStopIgnore(void)
{
  if(Mock.uxIORead_IgnoreBool)
    Mock.uxIORead_CallInstance = CMock_Guts_MemNext(Mock.uxIORead_CallInstance);
  Mock.uxIORead_IgnoreBool = (char)0;
}

void uxIORead_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ioAddress addr, ioData cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uxIORead_CALL_INSTANCE));
  CMOCK_uxIORead_CALL_INSTANCE* cmock_call_instance = (CMOCK_uxIORead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uxIORead_CallInstance = CMock_Guts_MemChain(Mock.uxIORead_CallInstance, cmock_guts_index);
  Mock.uxIORead_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_uxIORead(cmock_call_instance, addr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(ioData[sizeof(cmock_to_return) == sizeof(ioData) ? 1 : -1])); /* add ioData to :treat_as_array if this causes an error */
}

void uxIORead_AddCallback(CMOCK_uxIORead_CALLBACK Callback)
{
  Mock.uxIORead_IgnoreBool = (char)0;
  Mock.uxIORead_CallbackBool = (char)1;
  Mock.uxIORead_CallbackFunctionPointer = Callback;
}

void uxIORead_Stub(CMOCK_uxIORead_CALLBACK Callback)
{
  Mock.uxIORead_IgnoreBool = (char)0;
  Mock.uxIORead_CallbackBool = (char)0;
  Mock.uxIORead_CallbackFunctionPointer = Callback;
}

void uxIORead_CMockIgnoreArg_addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_uxIORead_CALL_INSTANCE* cmock_call_instance = (CMOCK_uxIORead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.uxIORead_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_addr = 1;
}

void vIOWrite(ioAddress addr, ioData data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vIOWrite_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_vIOWrite);
  cmock_call_instance = (CMOCK_vIOWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vIOWrite_CallInstance);
  Mock.vIOWrite_CallInstance = CMock_Guts_MemNext(Mock.vIOWrite_CallInstance);
  if (Mock.vIOWrite_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.vIOWrite_CallbackBool &&
      Mock.vIOWrite_CallbackFunctionPointer != NULL)
  {
    Mock.vIOWrite_CallbackFunctionPointer(addr, data, Mock.vIOWrite_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_addr)
  {
    UNITY_SET_DETAILS(CMockString_vIOWrite,CMockString_addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_addr), (void*)(&addr), sizeof(ioAddress), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_vIOWrite,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_data), (void*)(&data), sizeof(ioData), cmock_line, CMockStringMismatch);
  }
  if (Mock.vIOWrite_CallbackFunctionPointer != NULL)
  {
    Mock.vIOWrite_CallbackFunctionPointer(addr, data, Mock.vIOWrite_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_vIOWrite(CMOCK_vIOWrite_CALL_INSTANCE* cmock_call_instance, ioAddress addr, ioData data);
void CMockExpectParameters_vIOWrite(CMOCK_vIOWrite_CALL_INSTANCE* cmock_call_instance, ioAddress addr, ioData data)
{
  memcpy((void*)(&cmock_call_instance->Expected_addr), (void*)(&addr),
         sizeof(ioAddress[sizeof(addr) == sizeof(ioAddress) ? 1 : -1])); /* add ioAddress to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_addr = 0;
  memcpy((void*)(&cmock_call_instance->Expected_data), (void*)(&data),
         sizeof(ioData[sizeof(data) == sizeof(ioData) ? 1 : -1])); /* add ioData to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_data = 0;
}

void vIOWrite_CMockIgnore(void)
{
  Mock.vIOWrite_IgnoreBool = (char)1;
}

void vIOWrite_CMockStopIgnore(void)
{
  Mock.vIOWrite_IgnoreBool = (char)0;
}

void vIOWrite_CMockExpect(UNITY_LINE_TYPE cmock_line, ioAddress addr, ioData data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vIOWrite_CALL_INSTANCE));
  CMOCK_vIOWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_vIOWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.vIOWrite_CallInstance = CMock_Guts_MemChain(Mock.vIOWrite_CallInstance, cmock_guts_index);
  Mock.vIOWrite_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_vIOWrite(cmock_call_instance, addr, data);
}

void vIOWrite_AddCallback(CMOCK_vIOWrite_CALLBACK Callback)
{
  Mock.vIOWrite_IgnoreBool = (char)0;
  Mock.vIOWrite_CallbackBool = (char)1;
  Mock.vIOWrite_CallbackFunctionPointer = Callback;
}

void vIOWrite_Stub(CMOCK_vIOWrite_CALLBACK Callback)
{
  Mock.vIOWrite_IgnoreBool = (char)0;
  Mock.vIOWrite_CallbackBool = (char)0;
  Mock.vIOWrite_CallbackFunctionPointer = Callback;
}

void vIOWrite_CMockIgnoreArg_addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_vIOWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_vIOWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.vIOWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_addr = 1;
}

void vIOWrite_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_vIOWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_vIOWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.vIOWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

